mtree support added

diff --git a/contrib/integrity b/contrib/integrity
--- a/contrib/integrity
+++ b/contrib/integrity
@@ -3,22 +3,25 @@
 
 BACKUP="/integrity"
 HASHDIR="/hashdeep"
-# Ubuntu hashdeep TESTED OK
-#HASHDEEP="/usr/bin/hashdeep"
-# FreeBSD md5deep TESTED OK
-HASHDEEP="/usr/local/bin/md5deep"
-# Ubuntu hasdeep configuration
+
+# Ubuntu utilities and configuration
+# HASHDEEP="/usr/bin/hashdeep"
 # HASHDEEPCONF="-w -o f -l -r -x -k"
-# FreeBSD md5deep configuration
+# MTREE="/usr/bin/fmtree"
+#
+# FreeBSD utilities and configuration
+HASHDEEP="/usr/local/bin/md5deep"
 HASHDEEPCONF="-w -o f -l -r -x"
+MTREE="/usr/sbin/mtree"
+
 [ -f ~/.integrity ] && . ~/.integrity
 
 USAGE="$(basename "$0") [-h|--help] [-s|--silent] [-c|--commands] [-l|--list]
           [-a|--all|<client>] -- check integrity
 where:
-    -h --help             show this help text
-    -s --silent           report only errors
-    -c --commands         list commands to create the hash files
+    -h --help             show this help
+    -s --silent           report errors only
+    -c --commands         list commands to create the hash and mtree files
     -l --list             list clients
     -a --all              check integrity of all clients
     <client>              check integrity of client"
@@ -32,13 +35,20 @@ fi
 function check-integrity {
 # Files not included in hash-files will be printed (VERBOSE only)
 # Changed files in the hash-files will be printed (hash error)
-	 (($VERBOSE)) && printf "[OK] integrity: $CLIENT check started\n"
+	 (($VERBOSE)) && printf "[OK] integrity: *** $CLIENT check started\n"
 	 if LOG=$(cd $BACKUP; $HASHDEEP $HASHDEEPCONF $HASHDIR/$CLIENT.hashdeep $CLIENT/ 2>&1); then
 	     (($VERBOSE)) && printf "[OK] integrity: $CLIENT hash correct\n"
-	     (($VERBOSE)) && [[ ! -z $LOG ]] && printf "[OK] hashdeep: $LOG\n"
+	     (($VERBOSE)) && [[ ! -z $LOG ]] && printf "[OK] integrity: hashdeep: $LOG\n"
 	 else
 	     printf "[ERR] integrity: $CLIENT hash error $?\n"
-	     printf "[ERR] hashdeep: $LOG\n"
+	     printf "[ERR] integrity: hashdeep: $LOG\n"
+	 fi
+	 if LOG=$(cd $BACKUP; $MTREE -f $HASHDIR/$CLIENT.mtree -p $CLIENT/ 2>&1); then
+	     (($VERBOSE)) && printf "[OK] integrity: $CLIENT mtree correct\n"
+	     (($VERBOSE)) && [[ ! -z $LOG ]] && printf "[OK] integrity: mtree: $LOG\n"
+	 else
+	     printf "[ERR] integrity: $CLIENT mtree error $?\n"
+	     printf "[ERR] integrity: mtree: $LOG\n"
 	 fi
 }
 
@@ -58,6 +68,8 @@ for i in "$@"; do
 	    printf "Commands to create the hash-files:\n"
 	    for i in $CLIENTS; do
 		printf "cd $BACKUP; $HASHDEEP -e -o f -l -r $i/ > $HASHDIR/$i.hashdeep \n"
+		printf "cd $BACKUP; $MTREE -c -k uname,gname,mode,time -p $i/ > $HASHDIR/$i.mtree \n"
+		printf "\n"
 	    done
 	    exit
 	    ;;
