Ubuntu tested OK

diff --git a/contrib/integrity b/contrib/integrity
--- a/contrib/integrity
+++ b/contrib/integrity
@@ -2,19 +2,20 @@
 #set -x
 
 BACKUP="/backup"
-#BACKUP="/export/backup/snapshots/hourly.0"
-MD5DIR="/md5"
-#MD5DIR="/export/md5"
-# Ubuntu hashdeep NOT TESTED
-#MD5DEEP="/usr/bin/hashdeep"
+HASHDIR="/export/hashdeep"
+# Ubuntu hashdeep TESTED OK
+#HASHDEEP="/usr/bin/hashdeep"
 # FreeBSD md5deep TESTED OK
-MD5DEEP="/usr/local/bin/md5deep"
-MD5DEEPCONF="-w -o f -l -r"
+HASHDEEP="/usr/local/bin/md5deep"
+# Ubuntu hasdeep configuration
+# HASHDEEPCONF="-w -o f -l -r -x -k"
+# FreeBSD md5deep configuration
+HASHDEEPCONF="-w -o f -l -r -x"
 
 USAGE="$(basename "$0") [-h|--help] [-l|--list] [-s|--silent] [-a|--all|<client>] -- check integrity
 where:
     -h --help             show this help text
-    -s --silent           report only errors
+    -s --silent           report errors only
     -l --list             list clients
     -a --all              check integrity of all clients
     <client>              check integrity of client"
@@ -25,20 +26,23 @@ if [ $# -lt $EXPECTED_ARGS ]; then
     exit
 fi
 
-# Command to create the hash-files
-# cd $BACKUP; $MD5DEEP -e -o f -l -r $CLIENT/ > $MD5DIR/$CLIENT.md5deep
-# Files not inclueded in hash-files will be printed
+# Command to create the hash-files (both FreeBSD and Ubuntu tested OK)
+# cd $BACKUP; $HASHDEEP -e -o f -l -r $CLIENT > $HASHDIR/$CLIENT.hashdeep
 function check-integrity {
-#	 echo "*** intergrity of $CLIENT ---------------------------------------"
-	 if (cd $BACKUP; $MD5DEEP $MD5DEEPCONF -x $MD5DIR/$CLIENT.md5deep $CLIENT); then
-	     (($VERBOSE)) && printf "[OK] integrity: $CLIENT md5 correct\n"
+# Files not included in hash-files will be printed (VERBOSE only)
+# Changed files  in the has-files will be printed (hash error)
+	 (($VERBOSE)) && printf "*** intergrity of $CLIENT ---------------------------------------\n"
+	 if LOG=$(cd $BACKUP; $HASHDEEP $HASHDEEPCONF $HASHDIR/$CLIENT.hashdeep $CLIENT 2>&1); then
+	     (($VERBOSE)) && printf "[OK] integrity: $CLIENT hash correct\n"
+	     (($VERBOSE)) && printf "$LOG\n"
 	 else
-	     printf "[ERR] integrity: $CLIENT md5 error $?\n"
+	     printf "[ERR] integrity: $CLIENT hash error $?\n"
+	     printf "$LOG\n"
 	 fi
 }
 
 VERBOSE=1
-CLIENTS=$(ls -1 $MD5DIR | cut -d'.' -f1)
+CLIENTS=$(cd $HASHDIR;ls -1 *.hashdeep | rev | cut -d'.' -f2- | rev)
 for i in "$@"; do
     case $i in
 	-h|--help)
